name: Tests
on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Test
        run: go test -v --covermode=count --coverprofile=./coverage.out

      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./codecov_report.txt
